# Generated by Django 3.2.5 on 2021-07-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cache_hw', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['id'], 'verbose_name': 'Author'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id'], 'verbose_name': 'Post'},
        ),
    ]
